feat: docset verify

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,3 +13,16 @@ jobs:
 
       - name: run script
         run: bash ./scripts/generate_docset.sh
+
+      - name: docset Verify
+        run: |
+          wget https://kapeli.com/feeds/zzz/docsetcontrib.tgz; tar -xzf docsetcontrib.tgz;
+          ./docsetcontrib --verify | tee output.txt;
+          echo output.txt;
+          passOrFail=$([ ${PIPESTATUS[0]} == 0  ] && echo "**PASS** 🟢" || echo "**FAIL** 🔴");
+          result="$(cat output.txt)";
+          result="${result//'%'/%25}";
+          result="${result//$'\n'/%0A}";
+          result="${result//$'\r'/%0D}";
+          echo "::set-output name=result_code::$result";
+          echo "::set-output name=passOrFail_code::$passOrFail";
